LootJS.modifiers(event => {
    event.addEntityLootModifier("zombie_island:runner",
        "zombie_island:runner_1",
        "zombie_island:runner_2",
        "zombie_island:runner_3",
        "zombie_island:runner_4",
        "zombie_island:walker",
        "zombie_island:walker_1",
        "zombie_island:walker_2",
        "zombie_island:walker_3",
        "zombie_island:walker_4",
        "zombie_island:caustic_x_walker",
        "zombie_island:insect_swarm_walker",
        "zombie_island:riot_gear_walker",
        "zombie_island:grenadier_walker",
        "zombie_island:shambler",
        "zombie_island:shambler_1",
        "zombie_island:shambler_2",
        "zombie_island:shambler_3",
        "zombie_island:shambler_4",
        "zombie_island:firefighter_walker",
        "zombie_island:hazmat_walker",
        "zombie_island:burning_walker",
        "zombie_island:shocking_walker",
        "zombie_island:incendiary_walker",
        "zombie_island:eat_courier")
        .removeLoot('rotted:rotten_brain')
        .addLoot('minecraft:feather').randomChance(0.9)
        .addLoot('minecraft:string').randomChance(0.5)
        .addLoot('minecraft:bone').randomChance(0.8)
        .addLoot('minecraft:coal').randomChance(0.5)
        .addLoot('minecraft:raw_iron').randomChance(0.3)
        .addLoot('minecraft:raw_copper').randomChance(0.4)
        .addLoot('minecraft:raw_gold').randomChance(0.1)

    event.addEntityLootModifier("rotted:marine",
        "rotted:shielder",
        "rotted:flusk",
        "rotted:adventurer",
        "rotted:miner",
        "rotted:farmer",
        "rotted:doctor",
        "minecraft:vindicator",
        "minecraft:evoker",
        "minecraft:witch",
        "minecraft:wither_skeleton",
        "minecraft:blaze",
        "minecraft:phantom")
        .addLoot('minecraft:bone').randomChance(0.9)
        .addLoot('minecraft:string').randomChance(0.9)
        .addLoot('minecraft:copper_ingot').randomChance(0.7)
        .addLoot('minecraft:redstone').randomChance(0.7)
        .addLoot('minecraft:quartz').randomChance(0.7)
        .addLoot('minecraft:iron_ingot').randomChance(0.6)
        .addLoot('minecraft:gold_ingot').randomChance(0.6)
        .addLoot('minecraft:amethyst_shard').randomChance(0.6)
        .addLoot('createbigcannons:cast_iron_ingot').randomChance(0.5)
        .addLoot('legendarysurvivaloverhaul:heart_fruit').randomChance(0.2)
        .addLoot('create:crushed_raw_zinc').randomChance(0.5)
        .addLoot('minecraft:diamond').randomChance(0.5)
        .addLoot('create:powdered_obsidian').randomChance(0.3)
        .addLoot('minecraft:ancient_debris').randomChance(0.3)

    event.addEntityLootModifier("minecraft:cave_spider",
        "eeeabsmobs:corpse_warlock",
        "tacz_npcs:terrorist_no_armor",
        "tacz_npcs:terrorist_scav_pistol_armored",
        "tacz_npcs:terrorist_scav",
        "mutantmonsters:mutant_zombie",
        "minecraft:ghast",
        "minecraft:slime",
        "minecraft:spider",
        "minecraft:ravager",
        "minecraft:silverfish",
        "minecraft:skeleton",
        "minecraft:zoglin")
        .addLoot('minecraft:redstone').randomChance(0.9)
        .addLoot('minecraft:diamond').randomChance(0.8)
        .addLoot('minecraft:amethyst_shard').randomChance(0.9)
        .addLoot('minecraft:iron_ingot').randomChance(0.9)
        .addLoot("minecraft:netherite_ingot").randomChance(0.6)
        .addLoot("create:cinder_flour").randomChance(0.8)
        .addLoot("create:polished_rose_quartz").randomChance(0.7)
        .addLoot("create:brass_ingot").randomChance(0.7)
        .addLoot("create:zinc_ingot").randomChance(0.7)
        .addLoot("create:andesite_alloy").randomChance(0.7)
        .addLoot("createbigcannons:cast_iron_ingot").randomChance(0.8)
        .addLoot("createbigcannons:nethersteel_ingot").randomChance(0.6)
        .addLoot("create:sturdy_sheet").randomChance(0.7)
        .addLoot("silence_s_defense_tower:driving_core_1").randomChance(0.5)
        .addLoot("silence_s_defense_tower:acid_core_1").randomChance(0.5)
        .addLoot("silence_s_defense_tower:hell_core_1").randomChance(0.5)

    event.addEntityLootModifier("themutantmobsmod:mutantstray",
        "aqua_creepers:aqua_creeper",
        "minecraft:creeper",
        "mutantmonsters:mutant_creeper",
        "themutantmobsmod:mutant_drowned",
        "tntslimes:tnt_slime",
        "themutantmobsmod:mutant_zombified_piglin",
        "eeeabsmobs:nameless_guardian",
        "mutantmonsters:mutant_skeleton",
        "mutantmonsters:mutant_enderman",
        "themutantmobsmod:gigaillager",
        "minecraft:zombie")
        .addLoot('minecraft:amethyst_shard').randomChance(0.9)
        .addLoot("minecraft:gold_block").randomChance(0.9)
        .addLoot("minecraft:redstone_block").randomChance(0.9)
        .addLoot("minecraft:emerald_block").randomChance(0.9)
        .addLoot("minecraft:diamond_block").randomChance(0.9)
        .addLoot("minecraft:netherite_block").randomChance(0.8)
        .addLoot("minecraft:iron_block").randomChance(0.9)
        .addLoot('minecraft:enchanted_golden_apple').randomChance(0.8)
        .addLoot("create:cinder_flour").randomChance(0.8)
        .addLoot("create:polished_rose_quartz").randomChance(0.7)
        .addLoot("create:brass_block").randomChance(0.7)
        .addLoot("create:zinc_block").randomChance(0.7)
        .addLoot("create:andesite_alloy_block").randomChance(0.7)
        .addLoot("createbigcannons:cast_iron_block").randomChance(0.8)
        .addLoot("createbigcannons:nethersteel_block").randomChance(0.6)
        .addLoot("create:sturdy_sheet").randomChance(0.7)
        .addLoot("create:industrial_iron_block").randomChance(0.7)
        .addLoot("legendarysurvivaloverhaul:morphine").randomChance(0.7)
        .addLoot("legendarysurvivaloverhaul:medikit").randomChance(0.5)
        .addLoot("legendarysurvivaloverhaul:tonic").randomChance(0.6)
        .addLoot("legendarysurvivaloverhaul:golden_apple_juice").randomChance(0.5)
        .addLoot("silence_s_defense_tower:hell_core_4").randomChance(0.4)
        .addLoot("silence_s_defense_tower:driving_core_4").randomChance(0.4)
        .addLoot("silence_s_defense_tower:acid_core_3").randomChance(0.4)
    
    event.addLootTypeModifier(LootType.CHEST)
    .addLoot('minecraft:bone').randomChance(0.8)
    .addLoot('minecraft:string').randomChance(0.8)
    .addLoot('minecraft:copper_ingot').randomChance(0.5)
    .addLoot('minecraft:redstone').randomChance(0.5)
    .addLoot('minecraft:quartz').randomChance(0.5)
    .addLoot('minecraft:iron_ingot').randomChance(0.5)
    .addLoot('minecraft:gold_ingot').randomChance(0.5)
    .addLoot('minecraft:amethyst_shard').randomChance(0.5)
    .addLoot('createbigcannons:cast_iron_ingot').randomChance(0.4)
    .addLoot('legendarysurvivaloverhaul:heart_fruit').randomChance(0.1)
    .addLoot('create:crushed_raw_zinc').randomChance(0.4)
    .addLoot('minecraft:diamond').randomChance(0.4)
    .addLoot('create:powdered_obsidian').randomChance(0.2)
    .addLoot('minecraft:ancient_debris').randomChance(0.2)
    .addLoot("legendarysurvivaloverhaul:purified_water_bottle").randomChance(0.7)
    .addLoot("legendarysurvivaloverhaul:pumpkin_juice").randomChance(0.5)
    .addLoot("legendarysurvivaloverhaul:melon_juice").randomChance(0.5)
    .addLoot("legendarysurvivaloverhaul:chorus_fruit_juice").randomChance(0.5)
    .addLoot("legendarysurvivaloverhaul:carrot_juice").randomChance(0.5)
    .addLoot("legendarysurvivaloverhaul:cactus_juice").randomChance(0.5)
    .addLoot("legendarysurvivaloverhaul:apple_juice").randomChance(0.5)
    .addLoot("legendarysurvivaloverhaul:morphine").randomChance(0.4)
    .addLoot("legendarysurvivaloverhaul:healing_herbs").randomChance(0.6)
    .addLoot("legendarysurvivaloverhaul:bandage").randomChance(0.3)
    .addLoot("legendarysurvivaloverhaul:plaster").randomChance(0.4)
})