StartupEvents.registry("block", (event) => {
    event.create("military_casing")
    .displayName("军用外壳")
    .material("stone")
    .hardness(5.0)
    .resistance(2.0)
    .requiresTool(true)
    .tagBlock("mineable/pickaxe")
    .tagBlock('minecraft:needs_stone_tool')
    event.create("steel_block")
    .displayName("钢块")
    .material("metal")
    .hardness(6.5)
    .resistance(12.0)
    .requiresTool(true)
    .tagBlock("mineable/pickaxe")
    .tagBlock('minecraft:needs_iron_tool')
})
StartupEvents.registry("item", (event) => {
    event.create("coke_coal")
    .displayName("焦煤")
    event.create("steel_ingot")
    .displayName("钢锭")
})
StartupEvents.registry("fluid", (event) => {
    event.create("resin")
    .thickTexture("#FFFFCC")
    .color("#FFFFCC")
    .bucketColor("#FFFFCC")
    .displayName("树脂")
})