
["Better Time"]
	#If true, a date hud will show on your hud
	"Show Date Hud" = true
	"Date Hud X" = 10
	"Date Hud Y" = 10
	"Date Hud Color" = -1
	#If true, a day title will show on your screen next days
	"Show day title" = true

